lint notify:
  stage: test
  image: golangci/golangci-lint:v1.47.3-alpine@sha256:438f86d4521660b7c21cf06c50fc0bce4e26ba2a47434a88cc15495319e9c225
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
