lint notify:
  stage: test
  image: golangci/golangci-lint:v1.48.0-alpine@sha256:e9ce901b7974d641d6288b070fc619d199a823d0f696563fec8be90f19789b57
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
