lint notify:
  stage: test
  image: golangci/golangci-lint:v1.55.0-alpine@sha256:f3154040bf25ccabb1b7db1edd21debf750400855c814dfe74d9b793e5ef8362
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
