lint notify:
  stage: test
  image: golangci/golangci-lint:v1.55.2-alpine@sha256:22e4dd2bba6ad3c6ef918432b92329b51e82d55e470d268d315bfff6a160bceb
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
