lint notify:
  stage: test
  image: golangci/golangci-lint:v1.52.2-alpine@sha256:639dbebd312e31bb470ef70e83967eb2840a8cea39e857ac6494df2fe1b324fa
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
