lint notify:
  stage: test
  image: golangci/golangci-lint:v1.55.1-alpine@sha256:be89157ba90e80348e7551e8d17d2dc90f01dcdf33055a3e3ca85416137668b1
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
