lint notify:
  stage: test
  image: golangci/golangci-lint:v1.50.0-alpine@sha256:07adfc4af05aaff300f582b9f27300878101bf5c2e18d193bf9ea5f3e1041cbc
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
