lint notify:
  stage: test
  image: golangci/golangci-lint:v1.56.2-alpine@sha256:6324441960be114e0496d04c52395abe973b66db54ce51a5a9e64aaf08ac6299
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
