lint notify:
  stage: test
  image: golangci/golangci-lint:v1.52.0-alpine@sha256:eebb3f3f69d14a434ae261540d23951ee8794d0ce862362e4babc76c01000b5c
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
