lint notify:
  stage: test
  image: golangci/golangci-lint:v1.56.1-alpine@sha256:17f37c069f4a7c28c7397d8d2bc9eee256d5aebf403cf444927962c6fa37f8a7
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
