lint notify:
  stage: test
  image: golangci/golangci-lint:v1.61.0-alpine@sha256:61e2d68adc792393fcb600340fe5c28059638d813869d5b4c9502392a2fb4c96
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
