lint notify:
  stage: test
  image: golangci/golangci-lint:v1.57.1-alpine@sha256:f9722608039a3568101c4193f53ead34b724a0135dd34cef2a3d94234ff6e550
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
