lint notify:
  stage: test
  image: golangci/golangci-lint:v1.58.0-alpine@sha256:fb28daa680f971595da14483eacbf58321daf7690516497d008e5f46eaf78001
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
