lint notify:
  stage: test
  image: golangci/golangci-lint:v1.51.2-alpine@sha256:d4441632fdd9787214ebcfe026339adb9ab24a94026df18c8835893bfcdc9e27
  timeout: 10m
  script:
    - cd notify
    - golangci-lint run ./...
