include:
  - local: frontend/.gitlab-ci.yml
  - local: backend/.gitlab-ci.yml
  - local: notify/.gitlab-ci.yml

stages:
  - test

variables:
  TILT_NAMESPACE: ci-${CI_PROJECT_PATH_SLUG}-${CI_PIPELINE_ID}
  DOCKER_HOST: tcp://dind:2375

deploy:
  stage: test
  image: tiltdev/tilt:v0.30.13@sha256:833dbb724ec8ac2d873f76aa9ceff144d03da92899826bc3e8346ac50293c5ee
  timeout: 10m
  script:
    - PROD=1 tilt ci
  after_script:
    - kubectl delete ns ${TILT_NAMESPACE} --wait=false
