include:
  - local: frontend/.gitlab-ci.yml
  - local: backend/.gitlab-ci.yml
  - local: notify/.gitlab-ci.yml

stages:
  - test

variables:
  TILT_NAMESPACE: ci-${CI_PROJECT_PATH_SLUG}-${CI_PIPELINE_ID}
  DOCKER_HOST: tcp://dind:2375

deploy:
  stage: test
  image: tiltdev/tilt:v0.37.7@sha256:da4c104087f6281e3b89d2e76983486ea0bd85478bb8e26f6fe033697caf6f12
  timeout: 10m
  script:
    - PROD=1 tilt ci
  after_script:
    - kubectl delete ns ${TILT_NAMESPACE} --wait=false
