include:
  - local: frontend/.gitlab-ci.yml
  - local: backend/.gitlab-ci.yml
  - local: notify/.gitlab-ci.yml

stages:
  - test

variables:
  TILT_NAMESPACE: ci-${CI_PROJECT_PATH_SLUG}-${CI_PIPELINE_ID}
  DOCKER_HOST: tcp://dind:2375

deploy:
  stage: test
  image: tiltdev/tilt:v0.33.14@sha256:786d1871ba04c18519efa3ee4ab53b84241da7970e076deed87a5f5a3da75aee
  timeout: 10m
  script:
    - PROD=1 tilt ci
  after_script:
    - kubectl delete ns ${TILT_NAMESPACE} --wait=false
