include:
  - local: frontend/.gitlab-ci.yml
  - local: backend/.gitlab-ci.yml
  - local: notify/.gitlab-ci.yml

stages:
  - test

variables:
  TILT_NAMESPACE: ci-${CI_PROJECT_PATH_SLUG}-${CI_PIPELINE_ID}
  DOCKER_HOST: tcp://dind:2375

deploy:
  stage: test
  image: tiltdev/tilt:v0.33.17@sha256:293a4b4a44fed1fa55bf2e2560ca76ac3dd6a3152e642a3de42a089a0a3ca40b
  timeout: 10m
  script:
    - PROD=1 tilt ci
  after_script:
    - kubectl delete ns ${TILT_NAMESPACE} --wait=false
