include:
  - local: frontend/.gitlab-ci.yml
  - local: backend/.gitlab-ci.yml
  - local: notify/.gitlab-ci.yml

stages:
  - test

variables:
  TILT_NAMESPACE: ci-${CI_PROJECT_PATH_SLUG}-${CI_PIPELINE_ID}
  DOCKER_HOST: tcp://dind:2375

deploy:
  stage: test
  image: tiltdev/tilt:v0.37.8@sha256:efd98da0f4086866e4562dd7761df40b445de3272c66b1d70ac217c5ede37f83
  timeout: 10m
  script:
    - PROD=1 tilt ci
  after_script:
    - kubectl delete ns ${TILT_NAMESPACE} --wait=false
