issues:
  exclude:
     - Using the variable on range scope `tt` in function literal
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
