apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-image
        ports:
          - name: service
            containerPort: 8080
          - name: admin
            containerPort: 8090
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
    - name: admin
      port: 8090
