lint backend:
  stage: test
  image: golangci/golangci-lint:v1.47.2-alpine@sha256:10ed4891fdd1f7249f5e39d7c17ea746ce26adada3c05686c6aa31290abcd180
  timeout: 10m
  script:
    - cd backend
    - golangci-lint run ./...
