lint backend:
  stage: test
  image: golangci/golangci-lint:v1.57.0-alpine@sha256:fc1a85ed43171ecc4a6cf378260d25f78f0b1ce2254eb97d42143bfe7a50de29
  timeout: 10m
  script:
    - cd backend
    - golangci-lint run ./...
