lint backend:
  stage: test
  image: golangci/golangci-lint:v1.49.0-alpine@sha256:6ee4d0f07a27602408dbe5e2205bf6e80e9e28d7bc84960ff8e8ee5c410cbeb1
  timeout: 10m
  script:
    - cd backend
    - golangci-lint run ./...
