lint backend:
  stage: test
  image: golangci/golangci-lint:v1.52.1-alpine@sha256:86eeb69f00a46a73f977c9868c4551dd1f60bef8186e097a288ed8885e3a0734
  timeout: 10m
  script:
    - cd backend
    - golangci-lint run ./...
