lint backend:
  stage: test
  image: golangci/golangci-lint:v1.45.0-alpine@sha256:e2e0e2d5016a35e80cce1c78f294384e006f4dd9e36fe39f8792a22c5ebd58e5
  timeout: 10m
  script:
    - cd backend
    - golangci-lint run ./...
