lint backend:
  stage: test
  image: golangci/golangci-lint:v1.46.2-alpine@sha256:6a09f1e87ecce4eab163470467cd88dab3a0efa31cb708ba6d514a6889816095
  timeout: 10m
  script:
    - cd backend
    - golangci-lint run ./...
