lint backend:
  stage: test
  image: golangci/golangci-lint:v1.58.1-alpine@sha256:a71d17adb616b7b34785ce63343fa50cc9764b3fd7aadf27ba69f07fe10c6382
  timeout: 10m
  script:
    - cd backend
    - golangci-lint run ./...
