lint backend:
  stage: test
  image: golangci/golangci-lint:v1.51.0-alpine@sha256:1c03377ae2cffd18b89671cee2ef84ed4f44516e0661e3e490fa09ae3621e496
  timeout: 10m
  script:
    - cd backend
    - golangci-lint run ./...
