lint backend:
  stage: test
  image: golangci/golangci-lint:v1.47.1-alpine@sha256:319ec089d7506f6707abb81e94336abbb2997f98bbf48d6600f22efec0097f81
  timeout: 10m
  script:
    - cd backend
    - golangci-lint run ./...
