lint backend:
  stage: test
  image: golangci/golangci-lint:v1.56.0-alpine@sha256:260ddbde65533a7a34deca97c4b171f70a16c5609ed42f1605d3b8cd20dab0ca
  timeout: 10m
  script:
    - cd backend
    - golangci-lint run ./...
