run:
  timeout: 5m

issues:
  exclude:
     - Using the variable on range scope `tt` in function literal
     - "`adn` is a misspelling of `and`"
     - ineffectual assignment to `ctx`
     - this value of `ctx` is never used
#  exclude-rules:
#    - path: _test\.go
#      linters:
#        #- gocyclo
#        #- errcheck
#        #- dupl
#        #- gosec
#        #- funlen
#        #- gochecknoglobals
        
linters:
  disable:
    - gomnd
    - testpackage
    - goerr113
    - lll
