apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dind
spec:
  ports:
    - port: 2375
  selector:
    app: docker-in-docker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-in-docker
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: docker-in-docker
  template:
    metadata:
      labels:
        app: docker-in-docker
    spec:
      containers:
        - name: docker
          image: docker:20.10.17-dind@sha256:f92b5715c425e1066cab3a4d32be7b6ccee26c6a1ca3ca7544f86c6554df9424
          args:
            - sh
            - -c
            - dockerd
              --host=tcp://127.0.0.1:2375
              --host=tcp://${POD_IP}:2375
              --insecure-registry=10.0.0.0/8
              --insecure-registry=172.16.0.0/12
              --insecure-registry=192.168.0.0/16
              --mtu=1200
          env:
            - name: DOCKER_DRIVER
              value: overlay2
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2375
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              memory: "6Gi"
              cpu: "500m"
            limits:
              memory: "6Gi"
              cpu: "2000m"
          securityContext:
            privileged: true
          readinessProbe:
            exec:
              command:
                - docker
                - version
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker
      volumes:
        - name: docker
          persistentVolumeClaim:
            claimName: docker
