apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-tests
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: e2e-tests
    spec:
      containers:
      - name: tests
        image: e2e-tests-image
      restartPolicy: Never
