apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-tests
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: e2e-tests
    spec:
      initContainers:
        - name: wait-for-backend
          image: curlimages/curl:7.70.0
          args:
            - /bin/sh
            - -c
            - >
              set -euxo pipefail;
              while ! curl --max-time 1 --fail --silent -v -o /dev/null http://backend:8080/ ; do echo ""; done
        - name: wait-for-frontend
          image: curlimages/curl:7.70.0
          args:
            - /bin/sh
            - -c
            - >
              set -euxo pipefail;
              while ! curl --max-time 1 --fail --silent -v -o /dev/null http://frontend:8000/ ; do echo ""; done
      containers:
      - name: tests
        image: e2e-tests-image
      restartPolicy: Never
