
k8s_yaml('deployment/tests.yaml')
docker_build(
  'e2e-tests-image',
  '.',
  dockerfile='deployment/Dockerfile',
)
k8s_resource(
  'e2e-tests',
  trigger_mode=TRIGGER_MODE_MANUAL,
  resource_deps=['backend', 'frontend'],
)
