apiVersion: batch/v1
kind: Job
metadata:
  name: backend-integration-tests
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: backend-integration-tests
    spec:
      initContainers:
        - name: wait-for-backend
          image: alpine
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -sw '%{http_code}' "http://backend:8080" -o /dev/null) -ne 200]; do
                sleep 1;
              done
      containers:
      - name: tests
        image: integration-tests-image
      restartPolicy: Never
