apiVersion: batch/v1
kind: Job
metadata:
  name: setup-s3-bucket
spec:
  backoffLimit: 20
  template:
    metadata:
      name: setup-s3-bucket
    spec:
      containers:
        - name: mc
          image: quay.io/minio/mc:RELEASE.2021-10-07T04-19-58Z
          command:
            - sh
            - -c
            - |
              set -euxo pipefail
              mc config host add minio http://minio:9000 $(cat /secret/minio/MINIO_ACCESS_KEY) $(cat /secret/minio/MINIO_SECRET_KEY)
              mc mb minio/dinghy --ignore-existing
              mc admin config set minio notify_webhook:dinghy auth_token="$(cat /secret/webhook/token)" endpoint="http://notify:8080/webhook" queue_limit=100000 queue_dir="/queue"
              mc admin service restart minio
              mc event add minio/dinghy arn:minio:sqs::dinghy:webhook --ignore-existing
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 100Mi
          volumeMounts:
            - name: webhook
              mountPath: "/secret/webhook"
              readOnly: true
            - name: minio
              mountPath: "/secret/minio"
              readOnly: true
      volumes:
        - name: webhook
          secret:
            secretName: notify
        - name: minio
          secret:
            secretName: minio
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-old-files
spec:
  backoffLimit: 20
  template:
    metadata:
      name: delete-old-files
    spec:
      containers:
        - name: mc
          image: quay.io/minio/mc:RELEASE.2021-10-07T04-19-58Z
          command:
            - sh
            - -c
            - |
              set -euxo pipefail
              mc config host add minio http://minio:9000 $(cat /secret/minio/MINIO_ACCESS_KEY) $(cat /secret/minio/MINIO_SECRET_KEY)
              mc rm -r --older-than 30d --force minio/dinghy
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 100Mi
          volumeMounts:
            - name: minio
              mountPath: "/secret/minio"
              readOnly: true
      volumes:
        - name: minio
          secret:
            secretName: minio
      restartPolicy: OnFailure
