apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - name: minio
      port: 9000
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
        app: minio
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2020-05-16T01-33-21Z
          args:
            - server
            - /home/shared
          env:
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              value: minio123
          ports:
            - name: http
              containerPort: 9000
          resources:
            limits:
              cpu: "100m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
          livenessProbe:
            tcpSocket:
              port: 9000
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - "sleep 10"
          volumeMounts:
            - name: data
              mountPath: /home/shared  
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
