apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
  labels:
    app: notify
spec:
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      containers:
      - name: notify
        image: notify-image
        ports:
          - name: service
            containerPort: 4080
#          - name: admin
#            containerPort: 4090
#        readinessProbe:
#          httpGet:
#            path: /healthz
#            port: 4090
---
apiVersion: v1
kind: Service
metadata:
  name: notify
spec:
  selector:
    app: notify
  ports:
    - name: http
      port: 4080
#    - name: admin
#      port: 4090
