apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
  labels:
    app: notify
spec:
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      containers:
      - name: notify
        image: notify-image
        ports:
          - name: service
            containerPort: 8080
          - name: grpc
            containerPort: 50051
        lifenessProbe:
          httpGet:
            path: /metrics
            port: 8080
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
---
apiVersion: v1
kind: Service
metadata:
  name: notify
spec:
  selector:
    app: notify
  ports:
    - name: http
      port: 8080
    - name: grpc
      port: 50051
