apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
  labels:
    app: notify
spec:
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      containers:
        - name: notify
          image: notify-image
          args:
            - --webhook-token-file=/secret/token
          env:
            - name: JAEGER_AGENT_HOST
              value: jaeger
            - name: JAEGER_AGENT_PORT
              value: "6831"
          ports:
            - name: service
              containerPort: 8080
            - name: grpc
              containerPort: 50051
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          volumeMounts:
            - name: secret
              mountPath: "/secret"
              readOnly: true
      volumes:
        - name: secret
          secret:
            secretName: notify
---
apiVersion: v1
kind: Service
metadata:
  name: notify
spec:
  selector:
    app: notify
  ports:
    - name: http
      port: 8080
    - name: grpc
      port: 50051
---
apiVersion: v1
kind: Secret
metadata:
  name: notify
type: Opaque
data:
  token: dG9rZW4xMjMK # token123
