apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      name: jaeger
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.18.0
          ports:
            - name: query
              containerPort: 16686
            - name: compact-thrift
              containerPort: 6831
              protocol: UDP
          readinessProbe:
            httpGet:
              path: /
              port: 16686
              scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
    - name: query
      port: 16686
    - name: compact-thrift
      port: 6831
      protocol: UDP
  selector:
    name: jaeger
