apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
#  strategy:
#    type: Recreate
#  terminationGracePeriodSeconds: 5
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-image
        ports:
          - containerPort: 8080
          - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
