apiVersion: batch/v1
kind: Job
metadata:
  name: backend-unit-tests
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: backend-unit-tests
    spec:
      containers:
      - name: tests
        image: unit-tests-image
      restartPolicy: Never
