name: Execute automated checks
on:
  - push
jobs:
# https://github.com/golangci/golangci-lint-action#how-to-use
  go-lint:
    name: Lint go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Lint go code with golangci-lint
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.54
          working-directory: backend
      - name: Lint go code with golangci-lint
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.54
          working-directory: notify
  go-test:
    name: Verify go tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup golang
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: '1.17.0'
      - name: Print go version
        run: go version
      - name: Execute go tests 
        run: GOPROXY=https://goproxy.io go test -v ./...
        working-directory: backend
      - name: Execute go tests 
        run: GOPROXY=https://goproxy.io go test -v ./...
        working-directory: notify
  tilt-ci-dev:
    name: Verify tilt ci (development images)
    runs-on: ubuntu-latest
    steps:
      - name: Remove unused binarys
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
      - name: Checkout git repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00 # v1.5.0
      - name: Install tilt cli
        uses: yokawasa/action-setup-kube-tools@af4ebb1af1efd30c5bd84a2e9773355ad6362a33 # v0.9.3
        with:
          setup-tools: |
            tilt
          tilt: 'v0.33.6'
      - name: Verify tilt ci
        run: |
          timeout 1200 tilt ci
  tilt-ci-prod:
    name: Verify tilt ci (production images)
    runs-on: ubuntu-latest
    steps:
      - name: Remove unused binarys
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
      - name: Checkout git repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00 # v1.5.0
      - name: Install tilt cli
        uses: yokawasa/action-setup-kube-tools@af4ebb1af1efd30c5bd84a2e9773355ad6362a33 # v0.9.3
        with:
          setup-tools: |
            tilt
          tilt: 'v0.33.6'
      - name: Verify tilt ci
        run: |
          PROD=1 timeout 1200 tilt ci
